services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - game-server
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run start -- -H 0.0.0.0 -p 3000"
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db

  game-server:
    build:
      context: ./game-server
      dockerfile: Dockerfile
    env_file:
      - ./game-server/.env.production
    ports:
      - "5000:5000"
    restart: unless-stopped